# Name of your application. Used to uniquely configure containers.
service: nenba
image: adammusa/nenba
servers:
  web:
    - 77.42.83.12
proxy:
  ssl: true
  host: nenba.alkimist.dev
  app_port: 3000
  healthcheck:
    path: /
registry:
  server: 127.0.0.1:5555
builder:
  arch: amd64

